name: Leveraged-ETF-Analysis
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - matplotlib
  - pandas
  - pandas-datareader
  - yfinance
  - ipywidgets
  - git+https://github.com/mementum/backtrader.git@0fa63ef4a35dc53cc7320813f8b15480c8f85517#egg=backtrader
